### ISSUE TITLE
ReTerminal Debian support

### ISSUE THREAD

**Issue by EverythingSmartHome** [Seeed-Studio/seeed-linux-dtoverlays#38] opened 2022-03-31 15:27 UTC
I am trying to get Debian to load on the ReTerminal rather than Ubuntu (which I see there is already workarounds for).

I have tried installing Debian 11 Bullseye using both the tested image and daily images, and I can boot the ReTerminal, it gets stuck not being able to load bluetooth and network, and then lands me at the login screen...great!

The issue is that I have no USB and so I can't login, and since there is no network I can't SSH either. I think if I could actually login to the CM4 I might have a chance of fixing it, but as of now I'm out of ideas.

Any tips/suggestions?

(I know I could use Ubuntu or another, but I have an application that requires Debian 11)

**Comment by bigbearishappy** [comment] 2022-04-01 01:30
The latest firmware of raspberrypi official firmware is already the bullseye. you can download and try it with this [link](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit).

**Comment by bigbearishappy** [comment] 2022-04-01 02:32
Also, you can try to use a usb-to-serial to connect you CM4. Just use the uart to login.

**Comment by EverythingSmartHome** [comment] 2022-04-01 09:36
Thank you - I have no idea why I didn't think of that, looking at it for too long!

I was able to login with the serial, the only thing that didn't work was that serial would load as normal till near the end, then suddenly the output would become garbled. I saw this note on the [Debian](https://wiki.debian.org/RaspberryPi4) page:

```
On a Raspberry Pi 4B 4G with bullseye/linux 5.10.13-1, the serial stopped working after the vc4 module was loaded. As a workaround, add module_blacklist=vc4 to the command line to make it work
```

So I mounted the ReTerminal to my Linux desktop (Windows cannot read the main partition) and then under /etc/modprobe.d/ I created a file called blacklist.conf and inside added the line:
```
blacklist vc4
```

Booted it back up and then I was able to login. The problem now is that the ethernet port or wifi is not working - any tips or suggestions there?

**Comment by EverythingSmartHome** [comment] 2022-04-01 15:51
Managed to get Wifi working which is very handy! So I then tried to install the drivers using these instructions:

https://wiki.seeedstudio.com/reTerminal/#install-reterminal-drivers-after-flashing-new-raspberry-pi-os-ubuntu-os-or-other-os

After quite a few errors I managed to get it to exit successfully, however on reboot the display still does not work.

Would appreciate if you have any insight!

Thanks

**Comment by bigbearishappy** [comment] 2022-04-02 07:22
> 
you can first check the dmesg to see if the LCD driver is working, following is the normal work log:
```
pi@raspberrypi:~ $ dmesg | grep "mipi_dsi\|DSI"
[    6.576059] [DSI]i2c_md_init:
[    6.576246] [DSI]i2c_md_probe:start
[    6.624217] i2c_mipi_dsi 1-0045: I2C read id: 0xc3
[    6.629237] [DSI]mipi_dsi_device:
[    6.888689] [DSI]i2c_md_probe:finished.
[    6.889784] [DSI]mipi_dsi_probe:
[    6.919745] [DSI]panel_prepare:
[    6.981697] [DSI]ili9881d_prepare:
[    7.109738] [DSI]panel_enable:
```

If not.You need to check if the dtbo file is in the right place(reTerminal.dtbo in /boot/overlays/).
And you need to check the config.txt to see if there is the following code in it:
```
dtoverlay=reTerminal
```
What's more. You need to check if the mipi_dsi.ko can be found in the following directory:
```
/lib/modules/`uname -r`
```

**Comment by franzos** [comment] 2022-04-18 09:05
I can confirm that this worked probably a month ago, when I last created an image for reTerminal with Debian 11 Bullseye. However, after a recent `apt update && apt upgrade`, and re-running the scripts from [here](https://wiki.seeedstudio.com/reTerminal/#install-reterminal-drivers-after-flashing-new-raspberry-pi-os-ubuntu-os-or-other-os), the display stopped working.

@bigbearishappy following your notes, I found a curious error:

```bash
$ dmesg | grep "mipi_dsi\|DSI"
[    6.248742] [DSI]i2c_md_init:
[    6.249014] [DSI]i2c_md_probe:start
[    6.252887] i2c_mipi_dsi 1-0045: I2C read id: 0xc3
[    6.254866] [DSI]mipi_dsi_device:
[    6.353287] [DSI]i2c_md_probe:finished.
[    6.365518] [DSI]mipi_dsi_probe:
[    6.592147] mipi_dsi fe700000.dsi.0: failed to attach dsi to host: -517
[    6.674595] [DSI]mipi_dsi_probe:
[    6.909334] [DSI]panel_prepare:
[    6.964558] [DSI]ili9881d_prepare:
[    7.972581] [drm:vc4_dsi_host_transfer [vc4]] *ERROR* DSI transfer failed, resetting: -110
[    7.972670] [DSI]ili9881d_prepare:No LCD connected,pls check your hardware!
[    7.978750] [DSI]panel_enable:
```

The `/boot/config.txt` remains unchanged and lists:

```
...
dtoverlay=reTerminal
dtoverlay=reTerminal-bridge
```

and the mentioned `mipi_dsi.ko` exists too:

```
/lib/modules/5.15.32-v8+/updates/dkms/mipi_dsi.ko
```

**Comment by EverythingSmartHome** [comment] 2022-04-18 19:22
@franzos Thanks for your input, certainly helps. In my case, when I run the first script and reboot, the machine never comes back on, even when connected via serial - no network connection either.

Do you have any tips for specifying which kernel to use when building?

**Comment by franzos** [comment] 2022-04-18 19:37
@EverythingSmartHome what do you mean by "never comes back on"? There's no serial output at all?

Double-check that you have these in the config:

```
enable_uart=1
uart_2ndstage=1
```

In any case, there should be some debug logs; At least early firmware?

**Comment by EverythingSmartHome** [comment] 2022-04-18 19:44
@franzos Before running the script [here](wget https://files.seeedstudio.com/wiki/ReTerminal/ubuntu/script1.sh), everything works except the display (serial works, Wifi works), then when I run the script and reboot as per the instructions, I get no serial output and no network connectivity - almost like the machine can no longer boot, but I can't get a display out to verify.

Uart and serial was enabled in the config.txt and cmdline.txt files but I didn't check the uart_2ndstage line, I will try that.

**Comment by franzos** [comment] 2022-04-18 19:47
@EverythingSmartHome I never tried that. This is what I'm using:

```bash
git clone --depth 1 https://github.com/Seeed-Studio/seeed-linux-dtoverlays
cd seeed-linux-dtoverlays
sudo ./scripts/reTerminal.sh
```

**Comment by n7ihq** [comment] 2022-04-25 00:51
> I can confirm that this worked probably a month ago, when I last created an image for reTerminal with Debian 11 Bullseye. However, after a recent `apt update && apt upgrade`, and re-running the scripts from [here](https://wiki.seeedstudio.com/reTerminal/#install-reterminal-drivers-after-flashing-new-raspberry-pi-os-ubuntu-os-or-other-os), the display stopped working.

I had the same problem trying to Raspberry Pi OS Bullseye.

Jim

**Comment by lakshanthad** [comment] 2022-04-25 05:53
Hello everyone,

The problem is that, LCD driver does not work well with the latest kernel 5.15. I have raised this issue and assigned our Software Enginner in charge of reTerminal to fix it. The issue happens after running the reTerminal.sh script.
https://github.com/Seeed-Studio/seeed-linux-dtoverlays/issues/40
Please wait patiently until it is fixed.

For now, please stick with the factory images available here:
https://wiki.seeedstudio.com/reTerminal-FAQ/#q2-how-can-i-flash-raspberry-pi-os-which-is-originally-shipped-with-reterminal

Or else, you could switch to kernel 5.10.x and try. Because it worked well before for Kernel 5.10.x.

Best Regards,
Lakshantha

**Comment by EverythingSmartHome** [comment] 2022-04-25 18:59
Thanks for the update, looking forward to the fix!

**Comment by lakshanthad** [comment] 2022-05-05 12:45
Hello everyone,

LCD is working fine now with the latest Bullseye (kernel 5.15) release:
https://github.com/Seeed-Studio/seeed-linux-dtoverlays/pull/41

Please check and close this PR if everything works as expected.

Thank you.

Best Regards,
Lakshantha

**Comment by EverythingSmartHome** [comment] 2022-05-05 14:11
> @lakshanthad thanks for your quick follow-up! It's working as expected.
> 
> ```
> Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
> ```

Did you just install Debian, connect via serial and run the ReTerminal script 1 and 2 to get it working? About to test!

**Comment by lakshanthad** [comment] 2022-05-17 11:42
@EverythingSmartHome Is everything working for you now?

If yes, this PR can be closed.

Thank you.

**Comment by bigbearishappy** [comment] 2024-10-15 09:05
Closing this issue. If you have any further problem. Please reopen it or create a new one.
Thank you guys~

**Closed by bigbearishappy** 2024-10-15 09:05 UTC
Labels: UAY, seeed-linux-dtoverlays
